### PR TITLE
Add ConfigurationBuilder API

### PR DESCRIPTION
**Pull request by cspray**

### CODE REVIEW

**Comment by cspray** [comment]
@enumag what do you think of this for the ConfigurationBuilder API? If this looks ok I'll continue with the testing and implementation.

**Comment by enumag** [comment]
Looks good. Personally I prefer an anonymous class.

**Comment by cspray** [comment]
Since #14 impacts the Configuration instance in a breaking manner I'm going to implement that first before continuing with this. Thanks for the feedback.

**Comment by enumag** [comment]
Agreed. By the way #6 is also breaking if we make some things nullable.

**Comment by cspray** [comment]
Yea, I'll be sure to include in CHANGELOG and release notes that this is a breaking change.

**Pull request merged**
